# Generated by Django 2.0.5 on 2018-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviename',
            name='availabletickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviename',
            name='ticketprice',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moviename',
            name='totaltickets',
            field=models.IntegerField(default=120),
        ),
    ]
