# Generated by Django 2.0.5 on 2018-05-09 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180509_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviedate', models.DateField()),
                ('movietime', models.TimeField()),
                ('bookingtime', models.DateTimeField(default=datetime.datetime(2018, 5, 9, 23, 11, 51, 956784))),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('moviename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.MovieName')),
                ('ticketuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.MyUser')),
            ],
        ),
    ]
