# Generated by Django 2.0.4 on 2018-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_movietheater'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatername', models.CharField(max_length=60)),
                ('theaterplace', models.CharField(max_length=20)),
            ],
        ),
    ]
