# Generated by Django 2.0.4 on 2018-05-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_movietheater'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MovieTheater')),
            ],
        ),
    ]
